# SNAPSHOT artifacts upload for every commit on develop branch

name: Snapshot Release

on:
  push:
    branches: [develop]

jobs:

  snapshotRelease:

    name: Publish To OSSRH Snapshot Repository
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Decrypt Key Ring File
        env:
          FILE_PASSPHRASE: ${{ secrets.FILE_PASSPHRASE }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="${FILE_PASSPHRASE}" --output secring.gpg secring.gpg.gpg

      - name: Publish To OSSRH Snapshot Repository
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASS: ${{ secrets.SIGNING_PASS }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew publish -Psigning.secretKeyRingFile=../secring.gpg -Psigning.password="${SIGNING_PASS}" -Psigning.keyId="${SIGNING_KEY_ID}" --stacktrace
